# Generated by Django 4.2.7 on 2024-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_report_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_uuid",
            field=models.CharField(default="PLACEHOLDER", max_length=200),
            preserve_default=False,
        ),
    ]
