# Generated by Django 4.2.7 on 2024-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(max_length=300),
        ),
    ]
