# Generated by Django 4.2.7 on 2024-03-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_report_report_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="file",
        ),
        migrations.CreateModel(
            name="ReportS3File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s3_key", models.CharField(max_length=1024)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="s3_files",
                        to="app.report",
                    ),
                ),
            ],
        ),
    ]
