# Generated by Django 4.2.7 on 2024-03-17 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_report_reason"),
        ("app", "0004_remove_report_file_reports3file"),
    ]

    operations = []
