# Generated by Django 4.2.7 on 2024-03-17 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_merge_20240317_0448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
