# Generated by Django 4.2.7 on 2024-03-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('New-Report', 'New-Report'), ('Report-Review-In-Progress', 'Report-Review-In-Progress'), ('Completed-Report-Review', 'Completed-Report-Review')], default='New-Report', max_length=50),
        ),
    ]
