# Generated by Django 4.2.7 on 2024-03-25 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_status_changed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('Report-Submitted-For-Review', 'Report-Submitted-For-Review'), ('Report-Review-Started', 'Report-Review-Started'), ('Report-Review-Completed', 'Report-Review-Completed')], default='Report-Submitted-For-Review', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
