# Generated by Django 4.2.7 on 2024-03-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_report_report_date'),
        ('app', '0011_report_report_status_changed_notification'),
    ]

    operations = [
    ]
