# Generated by Django 4.2.7 on 2024-03-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20240326_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_notes',
            field=models.CharField(default='No notes provided.', max_length=200),
        ),
    ]
