# Generated by Django 4.2.7 on 2024-04-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(default='No notes provided.'),
        ),
    ]
