# Generated by Django 4.2.7 on 2024-04-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_report_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(choices=[('Report-Submitted-For-Review', 'Report-Submitted-For-Review'), ('Report-Review-Started', 'Report-Review-Started'), ('Report-Review-Completed', 'Report-Review-Completed')], default='Report-Submitted-For-Review'),
        ),
    ]
